image: gcc:13

stages: [build, test]

build:
  stage: build
  script:
    - mkdir -p build
    - g++ -std=c++17 -O2 -o build/app main.cpp
  artifacts:
    paths: [build/app]

test:
  stage: test
  needs: [build]
  script:
    - ./build/app
