image: gcc:13

stages: [build, test, docs, deploy]

build:
  stage: build
  script:
    - mkdir -p build
    - g++ -std=c++17 -O2 -o build/app main.cpp
  artifacts:
    paths: [build/app]

test:
  stage: test
  needs: [build]
  script:
    - ./build/app
    

variables:
  DOXYFILE: Doxyfile

# Common tools for both jobs
.default_before_script: &default_before
  - apt-get update
  - apt-get install -y doxygen graphviz make

docs_html:
  stage: docs
  before_script:
    - *default_before
  script:
    - doxygen "$DOXYFILE"          # produces html/ and latex/
  artifacts:
    paths:
      - html/                      # full HTML site
    expire_in: 1 week

docs_pdf:
  stage: docs
  before_script:
    - *default_before
    # LaTeX bits for PDF
    - apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  script:
    - doxygen "$DOXYFILE"          # ensures latex/ exists (safe to run again)
    - cd latex
    - make                         # builds refman.pdf
    - cp refman.pdf ../documentation.pdf
  artifacts:
    paths:
      - documentation.pdf
    expire_in: 1 week

deploy_staging:
  stage: deploy
  needs: ["test"]
  environment:
    name: staging
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
  script:
    - echo "Deploying to staging..."
    - mkdir -p deployed
    - cp build/app deployed/
  artifacts:
    paths:
      - deployed/
    expire_in: 1 week

# Manual deploy to production from main
deploy_production:
  stage: deploy
  needs: ["test"]
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  when: manual
  script:
    - echo "Deploying to production..."
    - echo "Code copied to production server "
  artifacts:
    paths:
      - deployed/
    expire_in: 1 week

