name: Trigger GitLab (C++)

on:
  push:
    branches: [ "main" ]   # change if your default branch is different

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        env:
          API_URL: ${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/pipeline
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          set -euo pipefail
          echo "➡️  Triggering $API_URL for ref $GITHUB_REF_NAME"
          curl --fail-with-body -sS -X POST \
            -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            --data "ref=${GITHUB_REF_NAME}" \
            --data "variables[LANGUAGE]=cpp" \
            "$API_URL"
          echo "✅ Trigger sent for C++ project."
