name: Trigger GitLab (C++)

on:
  push:
    branches: [ "main" ]   # change if your default branch is different
  workflow_dispatch:       # let you run it manually from the Actions tab

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      GITLAB_URL: ${{ secrets.GITLAB_URL }}
      GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}   # <- C++ project’s numeric ID in GitLab
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}             # <- token that can access the C++ GitLab project
    steps:
      - name: Trigger GitLab pipeline
        run: |
          set -euo pipefail
          echo "➡️  Triggering ${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/pipeline for ref ${GITHUB_REF_NAME}"
          curl --fail-with-body -sS -X POST \
            -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            --data "ref=main" \
            --data-urlencode "variables[LANGUAGE]=cpp" \
            "${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/pipeline"
          echo ""
          echo "✅ Trigger sent."
