name: call-central-ci
on:
  push:
    branches: [ "main" ]   # change if your default branch differs
  workflow_dispatch:

jobs:
  trigger-gitlab:
    uses: AarifRahaman/ci-infra/.github/workflows/trigger-gitlab.yml@main
    with:
      gitlab_url: https://gitlab.com
      project_id: "74092627"
      ref: main
      language: "cpp"
      repo_url: "https://github.com/${{ github.repository }}"
    secrets:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
